# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{candle}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dougal MacPherson"]
  s.date = %q{2010-11-17}
  s.description = %q{A simple gem to retrieve metadata on files via Spotlight on OS X. In development}
  s.email = %q{hello@newfangled.com.au}
  s.extensions = ["ext/candle/extconf.rb"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "TODO.textile",
    "VERSION",
    "candle.gemspec",
    "ext/candle/candle.c",
    "ext/candle/candle.o",
    "ext/candle/extconf.rb",
    "lib/candle.rb",
    "lib/candle/image.rb",
    "spec/candle/images_spec.rb",
    "spec/candle_spec.rb",
    "spec/fixtures/composites/example.ai",
    "spec/fixtures/composites/example.eps",
    "spec/fixtures/composites/example.pdf",
    "spec/fixtures/composites/example.ps",
    "spec/fixtures/composites/example.svg",
    "spec/fixtures/images/example.gif",
    "spec/fixtures/images/example.jpg",
    "spec/fixtures/images/example.png",
    "spec/fixtures/images/example.psd",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/dougalmacpherson/candle}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Using OS X spotlight to retrieve file metadata}
  s.test_files = [
    "spec/candle/images_spec.rb",
    "spec/candle_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.1.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.1.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.1.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

